### ISSUE TITLE
Question: Technically necessary dependency on Android 8?

### ISSUE THREAD

**Issue by esrat** [woheller69/spritpreise#19]
Hi,
I just found your app on the f-droid-store and wanted to give it a try.
Sadly, I just noticed that I cannot install it on any of my devices. The highest version supported on my Samsung S5 Mini is is Android 6.0.1, even lower on the other devices.

Is it really necessary to restrict the usage of this fine, privacy friendly app to users of the most current devices?

Even security-driven apps (e.g. Threema) with hard dependencies on the operating system are still supporting Android 5 to not unnecessarily exclude users. I do not understand why an application which does only call an open API via HTTP needs to exclude so many users.

**Comment by woheller69** [comment]
Unfortunately every additional Android version makes code more complex because of changing requirements of the Android SDK which then have to be handled via if ... then ... clauses.
Android 8+ should cover more than 85% of current used Android devices

Thank Google for that...

Maybe you should upgrade your phone via a custom Rom.
