### ISSUE TITLE
[Feature request] Favorite gas stations

### ISSUE THREAD

**Issue by BluePixel4k** [woheller69/spritpreise#4]
Thank you for the great app! I have searched for a similar foss app like this some time ago, but there was no one.

I would like it if you can mark gas stations as favorites and they are displayed in an extra tab.
So that you can optionally see all your favorites after a restart of the app.

**Comment by woheller69** [comment]
"I have searched for a similar foss app like this some time ago, but there was no one."

    I also tried to find one. That's why I wrote it :-)

You can select favorite brands and they will be marked with a star.
But I won't implement a separate tab showing favorites. I want to keep the app mechanisms as close as possible to my RadarWeather app.
And that would break this requirement and would also strongly increase API calls (which tankerkoenig does not like...) because you would need separate API calls for each station.

**Comment by BluePixel4k** [comment]
> I also tried to find one. That's why I wrote it :-)

I thought about that last year too and also found the Tankerkönig API. 😄 But since I don't have any experience in programming Android apps and I didn't have the time, I let it go for now. 

> You can select favorite brands and they will be marked with a star.

I tested it also, but this feature inst useful for me, because I have no favorite brands, only favorite gas stations that are on the line for me and they tend to be among the cheapest.

> But I won't implement a separate tab showing favorites. I want to keep the app mechanisms as close as possible to my RadarWeather app.

Sad, as this is my most used feature from other gas apps. But I can also understand it, since it is of course a certain extra effort.

> And that would break this requirement and would also strongly increase API calls (which tankerkoenig does not like...) because you would need separate API calls for each station.

For this you can surely think of a workaround by limiting the number of favorite gas stations or you can only favorite gas stations that are available at the stored locations and are only displayed filtered in a separate tab.

---

Be warned, I will create other feature requests that may not match your approach / cause too much work. But just see these as inspirations to make the app even better. 😃

**Comment by woheller69** [comment]
my favorite station is usually the closest one with the best price for the gas type I need.
This is achieved with the widget and GPS feature. In Version V1.3, where you can select a type and sort according to price

**Comment by BluePixel4k** [comment]
Okay, I'll have a look at v1.3, at the latest when it is released at F-Droid.

**Comment by Poldi1977** [comment]
I can only agree with BluePixel4k. Being able to favor gas stations is one of the features that I also find very useful. Most of the time I want to know which gas station is the cheapest on my way home.

**Comment by Anke** [comment]
I'd like to able to mark special gas stations as favorites as well, since we are three adjoining towns and the closest gas station for me e.g. is next town. Maybe it would be possible to establish favorites like another filter, just making other gas stations invisible instead of using another tab? Hey, and thank you for this app!!!
